/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Experience {
    id: string;
    title: string;
    duration: string;
    description: string;
    company: string;
    skills: Array<string>;
    location: string;
}
export interface Skill {
    icon: string;
    name: string;
    level: string;
}
export interface SocialLink {
    url: string;
    icon: string;
    platform: string;
}
export interface Service {
    id: string;
    title: string;
    icon: string;
    description: string;
}
export interface Profile {
    bio: string;
    theme: Theme;
    name: string;
    role: string;
    photoUrl: string;
}
export interface Project {
    id: string;
    title: string;
    featured: boolean;
    description: string;
    githubUrl: string;
    imageUrl: string;
    projectUrl: string;
    techStack: Array<string>;
}
export interface ContactInfo {
    socialLinks: Array<SocialLink>;
    email: string;
    phone: string;
}
export enum Theme {
    dark = "dark",
    light = "light"
}
export interface backendInterface {
    addExperience(id: string, title: string, company: string, location: string, duration: string, description: string, skillsArray: Array<string>): Promise<void>;
    addOrUpdateProfile(name: string, role: string, bio: string, photoUrl: string, theme: Theme): Promise<void>;
    addOrUpdateProject(id: string, title: string, description: string, imageUrl: string, techStack: Array<string>, projectUrl: string, githubUrl: string, featured: boolean): Promise<void>;
    addService(id: string, title: string, description: string, icon: string): Promise<void>;
    addSkill(name: string, level: string, icon: string): Promise<void>;
    getAllExperiences(): Promise<Array<Experience>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllServices(): Promise<Array<Service>>;
    getContactInfo(): Promise<ContactInfo>;
    getExperience(id: string): Promise<Experience>;
    getFeaturedProjects(): Promise<Array<Project>>;
    getProfile(user: Principal): Promise<Profile>;
    getProject(id: string): Promise<Project>;
    getService(id: string): Promise<Service>;
    getSkills(): Promise<Array<Skill>>;
    setContactInfo(email: string, phone: string, socialLinks: Array<SocialLink>): Promise<void>;
}
import type { Profile as _Profile, Theme as _Theme } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExperience(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addOrUpdateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Theme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProfile(arg0, arg1, arg2, arg3, to_candid_Theme_n1(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProfile(arg0, arg1, arg2, arg3, to_candid_Theme_n1(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async addOrUpdateProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: string, arg6: string, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addService(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSkill(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExperiences();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getExperience(arg0: string): Promise<Experience> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperience(arg0);
            return result;
        }
    }
    async getFeaturedProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProjects();
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_Profile_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_Profile_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return result;
        }
    }
    async getService(arg0: string): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return result;
        }
    }
    async getSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkills();
            return result;
        }
    }
    async setContactInfo(arg0: string, arg1: string, arg2: Array<SocialLink>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactInfo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactInfo(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Profile_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n4(uploadFile, downloadFile, value);
}
function from_candid_Theme_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n6(uploadFile, downloadFile, value);
}
function from_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    theme: _Theme;
    name: string;
    role: string;
    photoUrl: string;
}): {
    bio: string;
    theme: Theme;
    name: string;
    role: string;
    photoUrl: string;
} {
    return {
        bio: value.bio,
        theme: from_candid_Theme_n5(uploadFile, downloadFile, value.theme),
        name: value.name,
        role: value.role,
        photoUrl: value.photoUrl
    };
}
function from_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): Theme {
    return "dark" in value ? Theme.dark : "light" in value ? Theme.light : value;
}
function to_candid_Theme_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    dark: null;
} | {
    light: null;
} {
    return value == Theme.dark ? {
        dark: null
    } : value == Theme.light ? {
        light: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
