/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'socialLinks' : Array<SocialLink>,
  'email' : string,
  'phone' : string,
}
export interface Experience {
  'id' : string,
  'title' : string,
  'duration' : string,
  'description' : string,
  'company' : string,
  'skills' : Array<string>,
  'location' : string,
}
export interface Profile {
  'bio' : string,
  'theme' : Theme,
  'name' : string,
  'role' : string,
  'photoUrl' : string,
}
export interface Project {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'githubUrl' : string,
  'imageUrl' : string,
  'projectUrl' : string,
  'techStack' : Array<string>,
}
export interface Service {
  'id' : string,
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface Skill { 'icon' : string, 'name' : string, 'level' : string }
export interface SocialLink {
  'url' : string,
  'icon' : string,
  'platform' : string,
}
export type Theme = { 'dark' : null } |
  { 'light' : null };
export interface _SERVICE {
  'addExperience' : ActorMethod<
    [string, string, string, string, string, string, Array<string>],
    undefined
  >,
  'addOrUpdateProfile' : ActorMethod<
    [string, string, string, string, Theme],
    undefined
  >,
  'addOrUpdateProject' : ActorMethod<
    [string, string, string, string, Array<string>, string, string, boolean],
    undefined
  >,
  'addService' : ActorMethod<[string, string, string, string], undefined>,
  'addSkill' : ActorMethod<[string, string, string], undefined>,
  'getAllExperiences' : ActorMethod<[], Array<Experience>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getExperience' : ActorMethod<[string], Experience>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getProject' : ActorMethod<[string], Project>,
  'getService' : ActorMethod<[string], Service>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'setContactInfo' : ActorMethod<
    [string, string, Array<SocialLink>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];