/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'projectUrl' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'icon' : IDL.Text,
  'platform' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'socialLinks' : IDL.Vec(SocialLink),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'theme' : Theme,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const Skill = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'level' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExperience' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Theme],
      [],
      [],
    ),
  'addOrUpdateProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSkill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getExperience' : IDL.Func([IDL.Text], [Experience], ['query']),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getService' : IDL.Func([IDL.Text], [Service], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'setContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'projectUrl' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const SocialLink = IDL.Record({
    'url' : IDL.Text,
    'icon' : IDL.Text,
    'platform' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'socialLinks' : IDL.Vec(SocialLink),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'theme' : Theme,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const Skill = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'level' : IDL.Text,
  });
  
  return IDL.Service({
    'addExperience' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Theme],
        [],
        [],
      ),
    'addOrUpdateProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSkill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getExperience' : IDL.Func([IDL.Text], [Experience], ['query']),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getService' : IDL.Func([IDL.Text], [Service], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'setContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };